# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc5d3645f75487db3430ff22a01b37608f540b0107f49ddb532bb83f4addef6ad239127c5e1ba30214eeed3d3839adc65db4ea4f7b891bd09a261372a4753ed3

test:
  secret_key_base: df6d66e44bd84d4cc1ffb28fedab3c110d5e9fcaeea5d7d01c74afbd131054d3b27c9138b49463958b110fe6345ffba99b344906a5eba2dcc8d48d63bb00d3b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
